# Generated by Django 4.2.13 on 2024-06-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubtitleProcess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, upload_to='public/subtitle_files'),
        ),
    ]
