# Generated by Django 4.2.13 on 2024-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubtitleProcess', '0002_video_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='s3_file',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitle_file',
            field=models.URLField(blank=True),
        ),
    ]
