# Generated by Django 4.2.13 on 2024-06-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubtitleProcess', '0003_video_s3_file_alter_video_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_subtitle_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_video_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
