# Generated by Django 4.2.13 on 2024-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubtitleProcess', '0004_video_is_subtitle_processed_video_is_video_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_video_uploaded',
        ),
    ]
